---
type: 'uio'
images:
  'uio_rhel8':
    'name':             'UiO Managed RHEL 8'
    'depricated':       'Outdated (UiO RHEL8)'
    'url':              'http://builder/'
    'latest':           'uio_rhel8-latest.qcow2'
    'builder_checksum': 'uio_rhel8-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':            'scsi'
      'hw_scsi_model':          'virtio-scsi'
      'hw_qemu_guest_agent':    'yes'
      'hw_machine_type':        'q35'
      'os_require_quiesce':     'yes'
      'os_type':                'linux'
  'uio_rhel9':
    'name':             'UiO Managed RHEL 9'
    'depricated':       'Outdated (UiO RHEL9)'
    'url':              'http://builder/'
    'latest':           'uio_rhel9-latest.qcow2'
    'builder_checksum': 'uio_rhel9-latest.md5'
    'min_ram':          1024
    'min_disk':         8
    'visibility':       'shared'
    'owner':            'nrec-images'
    'properties':
      'hw_disk_bus':               'scsi'
      'hw_scsi_model':             'virtio-scsi'
      'hw_qemu_guest_agent':       'yes'
      'hw_machine_type':           'q35'
      'hw_firmware_type':          'uefi'
      'hw_vif_multiqueue_enabled': 'yes'
      'os_require_quiesce':        'yes'
      'os_type':                   'linux'
