---
# r1 flavor used for vGPU NVIDIA L40S with 24GB GPU-memory
# for osl region (used by naic)
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 1000000
  hw_rng:rate_period: 60
  aggregate_instance_extra_specs:type: 's== vgpul40s'
  resources:VGPU: '1'
  trait:CUSTOM_NREC_VGPU_L40S_24G: 'required'
gr1.L40S.24g:
  'gr1.L40S.24g.4xlarge':
    vcpus: 16
    ram: 122880
    disk: 200
