---
# C1 2TB disk optimized flavor used for sHPC
public: false
properties:
  hw_rng:allowed: 'True'
  hw_rng:rate_bytes: 2048
  hw_rng:rate_period: 1
  aggregate_instance_extra_specs:type: 's== shpc_cpu'
shpc.c1ad4:
  'shpc.c1ad4.2xlarge':
    vcpus: 8
    ram: 16384
    disk: 2000
  'shpc.c1ad4.4xlarge':
    vcpus: 16
    ram: 32768
    disk: 2000
  'shpc.c1ad4.8xlarge':
    vcpus: 32
    ram: 65536
    disk: 2000
  'shpc.c1ad4.16xlarge':
    vcpus: 64
    ram: 131072
    disk: 2000
