---
desc:   'Manage hypervisors/compute hosts'
actions:
  list:       'List all hypervisors'
  show:       'Show hypervisor details'
  instances:  'List all instances on hypervisor'
  add:        'Add host to aggregate'
  remove:     'Remove host from aggregate'
  move:       'Move host between aggregates'
  enable:     'Enable hypervisor'
  disable:    'Disable hypervisor'
  users:      'List users with instances in aggregate'

opt_args:
  'host':
    'sub':      ['add', 'remove', 'move', 'show', 'instances', 'enable', 'disable']
    'metavar':  'host'
    'help':     'Hypervisor host. Use either hostname or FQDN'
  'aggregate':
    'sub':      ['add', 'remove', 'move', 'users']
    'metavar':  'aggregate'
    'weight':   10
    'help':     'Aggreate name'
  '-t':
    'sub':      ['instances']
    'dest':     'type'
    'help':     'instance project type'
    'choices':  ['admin', 'demo', 'personal', 'research', 'education', 'course', 'test', 'hpc']
  '-a':
    'sub':      ['list']
    'dest':     aggregate
    'default':  'all'
    'help':     Limit list to one aggregate
  '-v':
    'sub':      ['list']
    'dest':     'verbose'
    'help':     'Be more verbose'
    'action':   'store_const'
    'const':    true
    'default':  false
