---
# Use empty value for None
desc: 'Manage images in current region! Use <action> -h for help on each action'
actions:
  'list':         'List all images. Output depends on visibility, tags and status'
  'update':       'Update images from config file'
  'usage':        'Check image usage. Output depends on visibility, tags and status'
  'purge':        'Delete unused deactive images'
  'grant':        'Grant access to a shared image'
  'revoke':       'Revoke access to a shared image'
  'list-access':  'List project with access to shared images'
  'retire':       'Retire manage images. Hint: Move config to retire.yaml and use this as config'
opt_args:
  '--domain':
    'dest':     'domain'
    'help':     'openstack domain to use'
    'default':  'Dataporten'
    'weight':   60
  '--detailed':
    'sub':      ['usage']
    'dest':     'detailed'
    'help':     'show detailed list'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--skip-cleanup':
    'sub':      ['update']
    'dest':     'skip_cleanup'
    'help':     'skip cleanup of downloaded images'
    'action':   'store_const'
    'const':    true
    'default':  false
  '-i':
    'sub':      ['update', 'retire']
    'dest':     'image_config'
    'help':     'config file under config/images/'
    'default':  'default.yaml'
  '-s':
    'sub':      ['list', 'usage']
    'dest':     'status'
    'help':     'image status'
    'default':  'active'
    'choices':  ['active', 'deactive']
  '-v':
    'sub':      ['list', 'usage', 'purge']
    'dest':     'visibility'
    'help':     'image visibility'
    'default':  'public'
    'choices':  ['public', 'private', 'shared']
  '-t':
    'sub':      ['list', 'usage', 'purge', 'grant', 'revoke', 'list-access']
    'dest':     'type'
    'help':     'image type tag'
    'default':  'all'
  '-n':
    'sub':      ['list', 'usage', 'purge', 'grant', 'revoke', 'list-access', 'update']
    'dest':     'name'
    'help':     'image name tag (short name)'
  'name':
    'sub':      ['retire']
    'metavar':  'name'
    'help':     'Image short name. Must be both in config file and name tag for active image'
  '-p':
    'sub':      ['grant', 'revoke']
    'dest':     'project'
    'help':     'project name to grant image access'
    'required': true
  '--project-by-id':
    'sub':      ['revoke']
    'dest':     'project_by_id'
    'help':     'Option "-p" specifies project ID, bypasses project check'
    'action':   'store_const'
    'const':    true
    'default':  false
  '--limit':
    'sub':      ['purge']
    'dest':     'limit'
    'help':     'limit number of deleted images'
  '--force':
    'sub':      ['grant', 'revoke', 'purge', 'retire']
    'dest':     'force'
    'help':     'skip interactive confirmation'
    'action':   'store_const'
    'const':    true
    'default':  false
