---
desc: 'Manage Sensu'
actions:
  delete:        'Delete host from Sensu'
  silence:       'Silence host'
  unsilence:     'Unsilence host'
  list-silenced: 'Lists silenced hosts'
opt_args:
  '-H':
    'sub':      ['delete','silence','unsilence']
    'dest':     'host'
    'help':     'Hostname'
    'required': True
  '-e':
    'sub':      ['silence']
    'dest':     'expire'
    'help':     'Duration of silence entry in seconds'
    'required': False
  '-r':
    'sub':      ['silence']
    'dest':     'reason'
    'help':     'Reason for silencing'
    'required': False
    'default':  'Silenced by himlarcli'
